 CREATE TABLE IF NOT EXISTS baskets (
     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     total_price NUMERIC,
     quantity_books BIGINT,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    basket_id BIGINT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    password VARCHAR(255),
    CONSTRAINT fk_basket FOREIGN KEY (basket_id) REFERENCES baskets(id)
 );

    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
 ------------------------
 CREATE TABLE IF NOT EXISTS authors (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name VARCHAR(255) NOT NULL,
      surname VARCHAR(255) NOT NULL,
      middle_name VARCHAR(255),
      pseudonym VARCHAR(255)
   );

   CREATE INDEX IF NOT EXISTS idx_authors_surname ON authors(surname);
   CREATE INDEX IF NOT EXISTS idx_authors_pseudonym ON authors(pseudonym);

   ------------------------
   CREATE TABLE IF NOT EXISTS publishers (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          description VARCHAR(255),
          country VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
       );

       CREATE INDEX IF NOT EXISTS idx_publishers_country ON publishers(country);

   ------------------------
   CREATE TABLE IF NOT EXISTS publisher_series (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          publisher_id BIGINT NOT NULL,
          name VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT fk_publishers FOREIGN KEY (publisher_id) REFERENCES publishers(id)
       );

       CREATE INDEX IF NOT EXISTS idx_publisher_series_publisher_id ON publisher_series(publisher_id);
   -------------------------------
CREATE TYPE book_genre AS ENUM('HORROR', 'COMEDY', 'ROMANTIC', 'DRAMA', 'THRILLER', 'NON-FICTION');

CREATE TABLE IF NOT EXISTS books (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    genre book_genre NOT NULL,
    publisher_id BIGINT NOT NULL,
    series_id BIGINT,
    price NUMERIC NOT NULL,
    isbn VARCHAR(255),
    release_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(255) NOT NULL,
    pages BIGINT NOT NULL,
    weight BIGINT,
    review_count BIGINT NOT NULL,
    average_rating BIGINT NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES authors(id),
    CONSTRAINT fk_publisher FOREIGN KEY (publisher_id) REFERENCES publishers(id),
    CONSTRAINT fk_series FOREIGN KEY (series_id) REFERENCES publisher_series(id)
 );

 CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);

-------------------------------------
CREATE TABLE IF NOT EXISTS basket_detail (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    basket_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    price NUMERIC NOT NULL,
    quantity BIGINT NOT NULL,
    CONSTRAINT fk_basket FOREIGN KEY (basket_id) REFERENCES baskets(id),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id)
 );

 CREATE INDEX IF NOT EXISTS idx_basket_detail_basket_id ON basket_detail(basket_id);
 CREATE INDEX IF NOT EXISTS idx_basket_detail_book_id ON basket_detail(book_id);
 -----------------------
    CREATE TABLE IF NOT EXISTS book_reviews (
       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       book_id BIGINT NOT NULL,
       reviewer_id BIGINT NOT NULL,
       text VARCHAR(255) NOT NULL,
       rating BIGINT NOT NULL,
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       CONSTRAINT fk_books FOREIGN KEY (book_id) REFERENCES books(id),
       CONSTRAINT fk_users FOREIGN KEY (reviewer_id) REFERENCES users(id)
    );

    CREATE INDEX IF NOT EXISTS idx_book_reviews_book_id ON book_reviews(book_id);

-------------------------------
    CREATE TABLE IF NOT EXISTS favorite_books (
       user_id BIGINT,
       book_id BIGINT,
       CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id),
       CONSTRAINT fk_books FOREIGN KEY (book_id) REFERENCES books(id)
    );
---------------------------------

    CREATE TABLE IF NOT EXISTS orders (
           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
           user_id BIGINT NOT NULL,
           recipient_name VARCHAR(255) NOT NULL,
           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
           updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
           CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id)
        );

        CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
