 CREATE TABLE IF NOT EXISTS baskets (
     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     total_price NUMERIC,
     quantity_books BIGINT,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    basket_id BIGINT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT fk_basket FOREIGN KEY (basket_id) REFERENCES baskets(id)
 );

    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
 ------------------------
 CREATE TABLE IF NOT EXISTS authors (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name VARCHAR(255) NOT NULL,
      surname VARCHAR(255) NOT NULL,
      middle_name VARCHAR(255),
      pseudonym VARCHAR(255)
   );

   CREATE INDEX IF NOT EXISTS idx_authors_surname ON authors(surname);
   ------------------------
   CREATE TABLE IF NOT EXISTS publishers (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          name VARCHAR(255),
          description VARCHAR(255),
          country VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
       );

       CREATE INDEX IF NOT EXISTS idx_publishers_country ON publishers(country);

   ------------------------
   CREATE TABLE IF NOT EXISTS publisher_series (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          publisher_id BIGINT NOT NULL,
          name VARCHAR(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT fk_publishers FOREIGN KEY (publisher_id) REFERENCES publishers(id)
       );
   -------------------------------
CREATE TYPE book_genre AS ENUM('HORROR', 'COMEDY', 'ROMANTIC', 'DRAMA', 'THRILLER');

CREATE TABLE IF NOT EXISTS books (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    genre book_genre NOT NULL,
    publisher_id BIGINT NOT NULL,
    series_id BIGINT,
    price NUMERIC NOT NULL,
    isbn VARCHAR(255),
    release_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(255) NOT NULL,
    pages BIGINT NOT NULL,
    weight BIGINT,
    review_count BIGINT NOT NULL,
    average_rating BIGINT NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES authors(id),
    CONSTRAINT fk_publisher FOREIGN KEY (publisher_id) REFERENCES publishers(id),
    CONSTRAINT fk_series FOREIGN KEY (series_id) REFERENCES publisher_series(id)
 );

 CREATE INDEX IF NOT EXISTS idx_books_title ON books(title);

-------------------------------------
CREATE TABLE IF NOT EXISTS basket_detail (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    basket_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    price NUMERIC NOT NULL,
    quantity BIGINT NOT NULL,
    total_price NUMERIC,
    title VARCHAR(200),
    CONSTRAINT fk_basket FOREIGN KEY (basket_id) REFERENCES baskets(id),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT uk_basket_book UNIQUE (basket_id, book_id)
 );
 -----------------------
    CREATE TABLE IF NOT EXISTS book_reviews (
       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       book_id BIGINT NOT NULL,
       reviewer_id BIGINT NOT NULL,
       text VARCHAR(255) NOT NULL,
       rating BIGINT NOT NULL,
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       CONSTRAINT fk_books FOREIGN KEY (book_id) REFERENCES books(id),
       CONSTRAINT fk_users FOREIGN KEY (reviewer_id) REFERENCES users(id)
    );

    CREATE INDEX IF NOT EXISTS idx_book_reviews_book_id ON book_reviews(book_id);

-------------------------------
    CREATE TABLE IF NOT EXISTS favorite_books (
       user_id BIGINT NOT NULL,
       book_id BIGINT NOT NULL,
       CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id),
       CONSTRAINT fk_books FOREIGN KEY (book_id) REFERENCES books(id),
       CONSTRAINT pk_favorite_books PRIMARY KEY (user_id, book_id)
    );
 ---------------------------------
 CREATE TYPE payment_status AS ENUM('Preparing', 'WaitPushTran', 'Authorized', 'PartPaid', 'Funded', 'FullyPaid',
 'Expired', 'Cancelled', 'Rejected', 'Refused', 'Closed', 'Voided', 'Refunded', 'Declined');

    CREATE TABLE IF NOT EXISTS payment_TXPG (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            payment_order_id BIGINT NOT NULL,
            is_card_saved BOOLEAN DEFAULT FALSE,
            order_id BIGINT,
            sum_of_pay NUMERIC,
            status VARCHAR,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
 ---------------------------------
    CREATE TABLE IF NOT EXISTS orders (
           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
           user_id BIGINT NOT NULL,
           payments_id BIGINT NOT NULL,
           recipient_name VARCHAR(255) NOT NULL,
           password VARCHAR(255) NOT NULL,
           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
           updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
           CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id),
           CONSTRAINT fk_payments FOREIGN KEY (payments_id) REFERENCES payment_TXPG(id)
        );

        CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);