services:
  test-db:
    image: postgres:15.4
    container_name: test_postgres_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - test-pgdata:/var/lib/postgresql/data
      - ./src/test/resources/init-test-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-pgdata:
