server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: pgadmin
    password: pgadmin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
jwt:
  secret: ${JWT_SECRET}

payment:
  order:
    type-rid: AK_Sale_Order_Base

  basic:
    auth: "TerminalSys/A.Konovalova@compassplus.com:1234"

  service:
      create-order-url: http://localhost:8004/order
      set-src-token-url: http://localhost:8004/order/{id}/set-src-token
      exec-tran-url: http://localhost:8004/order/{id}/exec-tran