server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:pgadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:pgadmin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}

payment:
  order:
    type-rid: AK_Sale_Order_Base

  basic:
    auth: "TerminalSys/A.Konovalova@compassplus.com:1234"

  service:
      create-order-url: http://localhost:8004/order
      set-src-token-url: http://localhost:8004/order/{id}/set-src-token
      exec-tran-url: http://localhost:8004/order/{id}/exec-tran