openapi: 3.0.4

info:
  title: Book store
  description: Книжный магазин
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

paths:

  /books:
    get:
      tags:
        - books

      summary: Получить книги
      operationId: getBooks
      parameters:
        - in: query
          name: id
          description: Параметр принимает id книги для поиска
          schema:
            type: integer
        - in: query
          name: authorId
          description: Параметр примнимает id автора для поиска
          schema:
            type: integer
        - in: query
          name: seriesId
          description: Параметр принимает id серии книги для поиска
          schema:
            type: integer
        - in: query
          name: publisherId
          description: Параметр принимает id издателя для поиска
          schema:
            type: integer
        - in: query
          name: genre
          description: Параметр принимает жанр для поиска
          schema:
            type: string
        - in: query
          name: limit
          description: Параметр указывает лимит вывода
          schema:
            type: integer
            default: 10

      responses:
        '200':
          description: Список книг
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'


        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /books/popular:
    get:
      tags:
        - books

      summary: Получить список популярных/новых книг
      operationId: getBooksPopular
      parameters:
        - in: query
          name: authorId
          description: Параметр указывает id для поиска по автору
          schema:
            type: integer
        - in: query
          name: publisher
          description: Параметр указывает издателя по поиска
          schema:
            type: string
        - in: query
          name: isPopular
          description: Параметр указывает значение популярности (популярно/непопулярно) для поиска
          schema:
            type: boolean
        - in: query
          name: isNew
          description: Параметр указывает значение новизны (новое/неновое)
          schema:
            type: boolean
        - in: query
          name: limit
          description: Параметр указывает лимит вывода
          schema:
            type: integer
            default: 10

      responses:
        '200':
          description: Список популярных книг

          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /books/authors/popular:
    get:
      tags:
        - authors

      summary: Поиск популярных авторов
      description: Поиск популярных авторов
      operationId: getAuthorsPopular
      responses:
        '200':
          description: OK

          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/purchased-books:
    get:
      tags:
        - account

      summary: Список приобретенных книг
      description: Получение списка приобретенных книг
      operationId: getPurchasedBooks

      security:
        - sessionAuth: []

      responses:
        '200':
          description: Список купленных книг

          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Неожиданная ошибка при покупке книг
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



  /account/favorite:
    post:
      tags:
        - account

      summary: Добавить книгу в избранное
      description: Добавление книги в избранное
      operationId: getFavoriteBooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bookId:
                  type: integer
      responses:
        '201':
          description: Книга добавлена в избранное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Неожиданная ошибка при добавлении в избранное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /account/basket:
    get:
      tags:
        - account

      summary: Корзина с книгами
      description: Получение корзины с книгами
      operationId: getBasket

      responses:
        '200':
          description: Список книг в корзине

          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /account/into/basket:
    post:
      tags:
        - account

      summary: Добавить книгу в корзину
      description: Добавление одной книги в корзину
      operationId: postIntoBasket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bookId:
                  type: integer
      responses:
        '201':
          description: Книга добавлена в корзину
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Неожиданная ошибка при добавлении в избранное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /payment/pay:
    post:
      tags:
        - payment

      summary: Оплата товаров в корзине
      description: Произведение оплаты корзины
      operationId: postPaymentPay
      security:
        - sessionAuth: []

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'

      responses:
        '200':
          description: Корзина оплачена

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

        '400':
          description: Ошибка оплаты корзины

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /payment/refund/{orderId}/{bookId}:
    post:
      tags:
        - payment

      summary: Возврат оплаты за книгу
      description: Возврат денежных средств, внесенных в качестве оплаты
      operationId: refundPay
      security:
        - sessionAuth: []

      parameters:
        - name: orderId
          in: path
          required: true
          description: Параметр для осуществления возврата денежных средств по определенному id заказа
          schema:
            type: integer

        - name: bookId
          in: path
          required: true
          description: Параметр для осуществления возврата денежных средств по определенному id книги
          schema:
            type: integer

      responses:
        '200':
          description: Оплата отменена

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefundResponse'

        '400':
          description: Ошибка отмены оплаты

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/basket/{bookId}:
    delete:
      tags:
        - account
      summary: Удаление товара из корзины
      description: Удаление товара из корзины по его id
      operationId: deleteBookById

      parameters:
        - name: bookId
          in: path
          required: true
          description: Параметр id книги для удаления
          schema:
            type: integer

      responses:
        '200':
          description: Товар удален
        '400':
          description: Ошибка при удалении товара
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /authors/{authorId}:
    get:
      tags:
        - authors

      summary: Информация об авторе
      description: Получение информации об авторе книг
      operationId: getAuthorById

      parameters:
        - name: authorId
          in: path
          required: true
          description: Параметр для идентификации по id для поиска информации об авторе
          schema:
            type: integer

      responses:
        '200':
          description: Вывод автора
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

        '400':
          description: Неожиданная ошибка при выводе информации об авторе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/register:
    post:
      tags:
        - auth

      summary: Регистрация пользователя
      description: Осуществление регистрации пользователя
      operationId: postRegister

      requestBody:
        required: true

        content:
          application/json:
            schema:
              type: object

              required:
                - email
                - password

              properties:
                email:
                  type: string

                password:
                  type: string

      responses:
        '200':
          description: Пользователь зарегистрирован
        '400':
          description: Регистрация не пройдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - auth

      summary: Ввод данных пользователя
      description: Ввод данных пользователя для осуществления входа в профиль
      operationId: postLogin

      requestBody:
        required: true

        content:
          application/json:
            schema:
              type: object

              required:
                - email
                - password

              properties:
                email:
                  type: string

                password:
                  type: string

      responses:
        '200':
          description: Вход выполнен успешно

          headers:
            Set-Cookie:
              description: Сессионный cookie
              schema:
                type: string

        '400':
          description: Вход не выполнен

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      tags:
        - auth

      summary: Выход из профиля
      description: Осуществление выхода из профиля
      operationId: postLogout

      security:
        - sessionAuth: []

      responses:
        '200':
          description: Сессия удалена (JSESSIONID)

        '400':
          description: Выход не выполнен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:

  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

  schemas:

    Book:
      type: object

      properties:
        id:
          type: integer

        title:
          type: string

        author:
          $ref: '#/components/schemas/Author'

        genre:
          $ref: '#/components/schemas/Genre'

        price:
          type: number
          format: double
          description: Информация цены

        publisher:
          type: string
          description: Информация об издателе

        ISBN:
          type: string

        series:
          type: string

        release:
          type: string

        description:
          type: string

        pages:
          type: string

        wight:
          type: integer

    Author:
      type: object

      properties:
        id:
          type: integer

        name:
          type: string

        surname:
          type: string

        middleName:
          type: string

        pseudonym:
          type: string

    Genre:
      type: object

      properties:
        id:
          type: integer

        name:
          type: string
          enum:
            - HORROR
            - COMEDY
            - ROMANTIC
            - DRAMA
            - THRILLER



    Basket:
      type: object

      properties:
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'

        totalPrice:
          type: number
          format: double

        quantityBooks:
          type: integer

        createdAt:
          type: string
          format: date-time

        updatedAt:
          type: string
          format: date-time

    PaymentResponse:
      type: object

      properties:
        orderId:
          type: integer

        sumOfPay:
          type: number
          format: double

        status:
          type: string
          enum:
            - CREATED
            - PENDING
            - PAID
            - FAILED
            - CANCELLED

        createdAt:
          type: string
          format: date-time

        message:
          type: string

        receiptUrl:
          type: string
          format: uri

    PaymentRequest:
      type: object

      properties:
        basket:
          $ref: '#/components/schemas/Basket'

        paymentMethod:
          type: string
          enum:
            - CARD
            - SBP
            - PAYPAL

        deliveryAddress:
          type: string

        recipientName:
          type: string

        recipientPhone:
          type: string

    RefundResponse:
      type: object

      properties:
        refund_amount:
          type: number
          format: double

        refundId:
          type: integer

        orderId:
          type: integer

        paymentId:
          type: string

        status:
          type: string
          enum:
            - PENDING
            - APPROVED
            - REJECTED
            - COMPLETED

        reason:
          type: string

        createdAt:
          type: string
          format: date-time


    Error:
      type: object

      properties:
        message:
          type: string